### ISSUE TITLE
Pages not found and PermissionDenied exception in tests

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1044]
This has been going on as far back as I can check old test runs.    Note that I was not getting these missing pages or permission errors locally until I deleted and recreated my venv, so it's possible there is some problem with a version of a module we are using in our requirements.txt ?

This is the oldest run that still has data, and it's showing the same thing (Click run test suite to view it)
https://github.com/bytedeck/bytedeck/runs/6438655994?check_suite_focus=true

![image](https://user-images.githubusercontent.com/10604391/174507108-aa89df49-2945-4834-9888-9f9197003cba.png)

**Comment by tylerecouture** [comment]
This might be related: https://code.djangoproject.com/ticket/10827

**Comment by tylerecouture** [comment]
Also this: https://stackoverflow.com/questions/26464838/getting-model-contenttype-in-migration-django-1-7

**Comment by tylerecouture** [comment]
https://stackoverflow.com/a/42791235/2700631

**Comment by 9921622** [comment]
# Permission denied error
issue here is that this shows up during tests:
```
Forbidden (Permission denied): <URL>
<CONSOLE ERROR HERE>
```
culprit of this error was: ``django.contrib.auth.mixins.UserPassesTestMixin.test_func`` overriden in the url's CBV.
If ``test_func`` is overriden and its output is ``False`` it will raise ``Forbidden (Permission denied)`` + ``<CONSOLE ERROR>``

Taking ``ProfileList`` as an example, the CBV assocciated with ``/quests/list/all`` overrides the ``django.contrib.auth.mixins.UserPassesTestMixin`` mixin.
ie:
```
class ProfileList(NonPublicOnlyViewMixin, UserPassesTestMixin, ListView):

   def test_func(self):
          return self.request.user.is_staff
```
In this case, if ``self.request.user.is_staff = False`` it will raise ``Forbidden (Permission denied)`` + ``<CONSOLE ERROR>``

A possible semi-solution is to add a middleware to silence to python error message (``<CONSOLE ERROR>``). Although, this doesnt remove the Forbidden (Permission denied) print.

However, this isnt really an issue since this behaviour is normal

# Not found message
issue here is that this shows up during tests:
```
Not Found: <URL>
```
culprit of this error was calling ``self.client.get`` or ``self.client.post`` on a url that does not exist
Most of these messages stem from test functions that are targeted on deleting an object then checking if it exist in the detail view.

ie:
```
@tag('do')
def test__a_random_test_function(self):
    self.client.get("/url-that-does-not-exist/")
```
will raise this message
```
Not Found: /url-that-does-not-exist/
```

Im not sure if there is a way to silence the print, but this behaviour is normal

**Comment by 9921622** [comment]
Also from #1047 
```
@9921622 As discussed, we're gonna drop this PR and leave as is, and you're gonna close 
the issue with a detail comment in the issue. Thanks for investigating and figuring them out!
```

I dont think i have permission to close this issue + i dont know how

**Comment by tylerecouture** [comment]
Perfect. Thanks!
