### ISSUE TITLE
Quest Approval Page Improvement - Don't Update Entire Screen Between Approvals

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#1349]
When I approve a quest, it would be great if rather than rerendering the page, it could just clear that particular quest submission. I find that I approve a quest and then go to the next quest and then it refreshes mid type (it has a delay between quest approval). I can change my habits, but a more optimal way would be for it clear the submission and I could keep approving.

**Comment by tylerecouture** [comment]
@9921622 Since you've now dabbled a bit in Ajax views, you should be able to do this via Ajax.  You'll also need to remove the entire quest element using JQuery (easy to do nicely and already part of the project) or vanilla JavaScript.

I'm not sure how this will handle django messages, so might need to pay around with that. For example, if a teacher approves 10 quests like this (via Ajax), the next time they load a new page ,are they going to get 10+ messages at the top of the screen?

**Comment by tylerecouture** [comment]
If there is a way to post those messages at the top live somehow (without loading the screen) that would be much better.
