### ISSUE TITLE
learn.bytedeck student list showing nobody ever submitting quests

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#1424]

**Comment by tylerecouture** [comment]
That might be because there are lots of students registered in the "Do not use" and "Do not use this Group" groups.  And those groups don't have a teacher assigned to them, or because most of the quest appear to be set to automatic approval.

![image](https://github.com/bytedeck/bytedeck/assets/10604391/23ae90f8-a601-4085-8129-602a8f92b67f)

![image](https://github.com/bytedeck/bytedeck/assets/10604391/a8cd77e3-df46-464e-ab85-94535716880c)

The course setup is weird on that deck, I'm not sure what the plan was with those groups or why they are there?

Most of the quests appear to me automatically approved, so there won't be anything to approve (however, the teacher assigned to a group would get email notifications if that's turned on, and if their email is verified)

I signed up as a test student and submitted a quest that requires teacher approval (Who owns your creations) and it shows up in the approval list for the assigned teacher (bytedeck.admin) as expected.

![image](https://github.com/bytedeck/bytedeck/assets/10604391/d629d677-b9dd-4f71-84f7-0aba12410eba)
