### ISSUE TITLE
Set Markrange model 'minimum_mark' field to unique=true and handle existing duplicates in databases

### ISSUE THREAD

**Issue by Dylan-RG-Patterson** [bytedeck/bytedeck#1461]
Due to an update to the mark calculation page that ensures duplicate MarkRanges aren't displayed, instances of two separate mark range objects with identical minimum marks are also seen as duplicates, and aren't displayed. In practice, there shouldn't be two MarkRange objects with the same minimum mark anyway, as their lines on the mark calculation graph would overlap. 

To account for the new change that renders duplicate 'minimum_mark' values obsolete, that field on the MarkRange model class should be given the unique=true option, to automatically prevent this situation from occuring.

A major issue, however, is that existing databases with MarkRange objects carrying duplicate values might exist, so handling of this data to prevent migration errors is required. 

In brief: Add unique=true option to 'minimum_mark' field in the MarkRange model class (courses.models.MarkRange), and handle duplicate 'minimum_mark' data in existing databases so migrations don't break.

example list of existing MarkRange objects (note 'Chillax Line' and 'A' have identical 'minimum_mark' values)
![image](https://github.com/bytedeck/bytedeck/assets/105619909/ba966bda-a333-49e9-9938-8b919522264f)

rendered mark calculation display ('Chillax Line' is not rendered because of its duplicate 'minimum_mark' value to 'A')
![image](https://github.com/bytedeck/bytedeck/assets/105619909/6ffc7e56-c51e-4652-af3e-2590d42606af)

**Comment by tylerecouture** [comment]
Note:  Because mark ranges can be different for different courses.  What we probably want is to just ensure that the SAME mark range isn't duplicated.  Because it's possible that two courses have a different mark range set but may share a similar min mark.  I actually think that we can ignore that case and just go with what we have, leaving min mark as NOT unique for this reason (but only one of them would show up if the student was in both courses)
