### ISSUE TITLE
Allow deletion of Semesters that have no students

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#1564]
If no students/courses are registered in a Semester, then you should be able to delete it.

Add a delete button to the Semester list for these semesters.  For semesters that do have students/courses, use an inactivated delete button with popup text explaining "Only semesters without any students registered can be deleted".

**Comment by 9921622** [comment]
This feature is pretty much implemented?
Unless you want to add a delete button to all semesters and have them active/inactive instead of just hidden/active

![image](https://github.com/bytedeck/bytedeck/assets/39788517/bd495702-4a48-4a4d-81ca-a5c62e1aca6e)
![image](https://github.com/bytedeck/bytedeck/assets/39788517/ecf7a692-f8ac-4aa4-904f-412a9e5ad4cf)
![image](https://github.com/bytedeck/bytedeck/assets/39788517/6c5ef1b9-80bc-44f2-879b-6c9a8b235f4a)

**Comment by tylerecouture** [comment]
@9921622 can you use GitBlame (VSCode add on) to see what commit those changes were made in?  That might have been me, but I don't remember! haha.  Then link to the commit in this issue.

**Comment by 9921622** [comment]
@tylerecouture 
Related issue: https://github.com/bytedeck/bytedeck/issues/1418
commit: https://github.com/bytedeck/bytedeck/commit/8d59c24f0178520517d04c308a31d4a73fc1633b

**Comment by tylerecouture** [comment]
Thank you. Duplicate of #1418, that's why this didn't get closed.
