### ISSUE TITLE
Unable to Delete or Hide Blocks

### ISSUE THREAD

**Issue by fjbagley** [bytedeck/bytedeck#855]
I have tried removing my All Day, C and D blocks from both the main site and the admin side, but get a 500 server error in both cases. Would be good to keep those old blocks hidden so no students get confused when registering.

**Comment by tylerecouture** [comment]
TODO: 

- [ ] Add an `active` field to blocks (default=True)
- [ ] If trying to delete a block that has past students in it, have a page recommend making the block inactive instead of just giving a 500 error
- [ ] Add the active field to the Block edit/create form
- [ ] Only display active=True blocks to students when they are registering for a course
