### ISSUE TITLE
Make usernames case insensitive

### ISSUE THREAD

**Issue by tylerecouture** [bytedeck/bytedeck#858]
When signing up on mobile devices, the auto capitalization that phones do is annoying and can cause sign in problems if they don't remember whether they used a cap or not.  So just make sign-in case insensitive!

Will also need to be unique on case-insensitive usernames too.

**Comment by yujinyuz** [comment]
This can be quite complicated since it requires changing the using a custom user model: https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#changing-to-a-custom-user-model-mid-project

OR

We can customize the authentication backend to be case insensitive and also update the `UserCreationForm` and some other registration forms to prevent duplicate case insensitive usernames

**Comment by tylerecouture** [comment]
Tweaking the form sounds way easier. We would need to also tweak the login form to submit all lowercase

**Comment by tylerecouture** [comment]
Could we just do this via forms?

If we create an admin command or migration to covert all existing usernames to lower case

Then the sign up and sign in forms all covert to lowercase, should be good?

**Comment by tylerecouture** [comment]
@yujinyuz I just tried this on the staging site (finally), and although it seems to work, it then lists all 780 users in the "multiple usernames" list.

**Comment by yujinyuz** [comment]
@tylerecouture Could you verify for me by looking into the db for the first few usernames?
```python
User.objects.filter(username__iexact="the_username")
```

And see if there are actually duplicates for that username?

**Comment by tylerecouture** [comment]
Closing this cus it's working, even though the admin command's feedback is buggy.
