### ISSUE TITLE
Quest w/o prereqs does not show up for students

### ISSUE THREAD

**Issue by aluxenburg** [bytedeck/bytedeck#936]
When I create a new quest, I must have a prerequisite for it to show up in maps and to the student in their quest list.
Once I have a prerequisite, it shows up in maps and quest list.
If I then remove the prerequisite, it stays in the maps (with prereq attached) and does not show up in student quest list.
https://edpb530.bytedeck.com/quests/available/
I have a quest ready to create a tutorial: Verification required example 1
You can see in this course that there are two quests that do show up for students... they do not have prereqs: Welcome to ByteDeck and Who Owns your creations.  Both were from the quests that came with the deck.... but I can't seem to make my own quest not have a prereq and just show up for students.

**Comment by tylerecouture** [comment]
A few clarification questions for you on this:

Re: no prereqs appearing for students: Can you confirm that quests with no prerequisites don't show up in students available quest list? They should.  For example the default intro quests has no prerequisites and that's how it shows up right at the beginning, so I'm wondering if it's something else preventing it.

By default students must join a course for quests to appear. Although there is an advanced quest option to allow a quest to appear even if students aren't registered in a course.

Related: what is the use case for quests without any prerequisite other than the Intro? Seems like any quest that should be available to everyone you would want to at least have the intro as a prerequisite, if not the Bytedeck proficiency badge (or whatever intro badge a deck uses)

Re Maps: do you have a suggestion how non-prereq quests should be mapped? We could create a special custom map that only contains non-prereq quests (though I would like to understand the use case for these kinds of quests)

Thanks!

**Comment by aluxenburg** [comment]
That is correct. I created a video tutorial and went back and forth (refreshing and using different browsers) between student and instructor views and the quest without pre-reqs did not show up in the student quests.

**Comment by aluxenburg** [comment]
By the way
This is not a priority item.

**Comment by tylerecouture** [comment]
I think I might know the cause of this.  Can you check two things for me?

1. If you grant a badge (any one) to one of these students, does the quest appear after?
2. If you create a new fake student, do the quests appear for them? (after they've joined a course)?

If it does, then the bug is because the quests available to students is cached, and creating a this new quest doesn't re-determine the quests available to them for some reason, until some other event.

**Comment by aluxenburg** [comment]
Sorry for the delay in responding. Swamped.
Yes. Both of those actions worked to reveal the quest to the students.
Again, Tylere... this is not a priority.

**Comment by tylerecouture** [comment]
Thank you!

Note to devs:   Need to trigger a recalculation of available quests for all students when a new quest is created without prereqs.  This is missed because the current trigger is a new prereq, but if the quest has no prereqs then it won't be triggered.

See prerequisites/signals.py

update_quest_conditions_all_users()

**Comment by yujinyuz** [comment]
@tylerecouture 


So if I understand corretctly, the current behavior is that it only updates user quests when saving or deleting a badge


```python
# src/prerequisites/signals.py:L48
@receiver([post_save, post_delete], sender=Badge, dispatch_uid="prerequisites.signals.update_conditions_met")
def update_conditions_met(sender, instance, *args, **kwargs):
    update_quest_conditions_all_users.apply_async(args=[1], queue='default', countdown=settings.CONDITIONS_UPDATE_COUNTDOWN)
```

And the solution is to include `Quest` creation as well?

So I just need to change the current function to accept multiple senders `[Bagde, Quest]`

**Comment by tylerecouture** [comment]
Most of the update signals come from the Prereq model.  This Badge based update is already a problem because it will run twice (once when the Badge model is updated, and also if the Badge's Prereq is updated) and the process is expensive.  But badges don't update too often, so currently living with it.

If we added Quest to this, then it would run the process every time anything was updated on a quest, a huge waste of resources.  It should only run when Prereq relevant fields are updated.

However, for this issue, we need a separate signal that receives the post_save on a quest, and check if that quest has prerequisites.  If it DOES have prerequisites, then we don't have to do anything, because it will get caught in the Prereq post_save signal.

If it DOESN'T have prerequisites, then currently nothing will happen.  So we need to run update_quest_conditions_all_users() in that specific case.

I hope that makes sense?
